export const CREATE_ROUTE_SUCCESS = "CREATE_ROUTE_SUCCESS";
export const UPDATE_ROUTE_SUCCESS = "UPDATE_ROUTE_SUCCESS";
export const USER_LOGOUT = "USER_LOGOUT";

export const SIDEBAR_OPEN = "SIDEBAR_OPEN";
export const SIDEBAR_CLOSE = "SIDEBAR_CLOSE";

export const LOAD_PHOTOS = "LOAD_PHOTOS";
export const SELECT_PHOTO = "SELECT_PHOTO";
export const RESET_GALLERY_STATE = "RESET_GALLERY_STATE";
export const SET_NEXT_PHOTO = "SET_NEXT_PHOTO";
export const SET_PREV_PHOTO = "SET_PREV_PHOTO";

export const ROUTE__FETCH_STARTED = "ROUTE__FETCH_STARTED";
export const ROUTE__FETCH_SUCCEEDED = "ROUTE__FETCH_SUCCEEDED";
export const ROUTE__FETCH_FAILED = "ROUTE__FETCH_FAILED";

export const ROUTE__SAVE_STARTED = "ROUTE__SAVE_STARTED";
export const ROUTE__SAVE_CREATE_SUCCEEDED = "ROUTE__SAVE_CREATE_SUCCEEDED";
export const ROUTE__SAVE_UPDATE_SUCCEEDED = "ROUTE__SAVE_UPDATE_SUCCEEDED";
export const ROUTE__SAVE_FAILED = "ROUTE__SAVE_FAILED";
export const ROUTE__SAVE_ENDED = "ROUTE__SAVE_ENDED";

export const ROUTE__REMOVE_STARTED = "ROUTE__REMOVE_STARTED";
export const ROUTE__REMOVE_SUCCEEDED = "ROUTE__REMOVE_SUCCEEDED";
export const ROUTE__REMOVE_FAILED = "ROUTE__REMOVE_FAILED";
export const ROUTE__REMOVE_ENDED = "ROUTE__REMOVE_ENDED";

export const ROUTE_GALLERY__FETCH_STARTED = "ROUTE_GALLERY/FETCH_STARTED";
export const ROUTE_GALLERY__FETCH_SUCCEEDED = "ROUTE_GALLERY/FETCH_SUCCEEDED";
export const ROUTE_GALLERY__FETCH_FAILED = "ROUTE_GALLERY/FETCH_FAILED";
export const ROUTE_GALLERY__SELECT_PHOTO = "ROUTE_GALLERY/SELECT_PHOTO";

export const ROUTE__FETCH_PHOTOS_STARTED = "ROUTE/FETCH_PHOTOS_STARTED";
export const ROUTE__FETCH_PHOTOS_SUCCEEDED = "ROUTE/FETCH_PHOTOS_SUCCEEDED";
export const ROUTE__FETCH_PHOTOS_FAILED = "ROUTE/FETCH_PHOTOS_FAILED";

export const ROUTE_GALLERY__UPLOAD_NEW_PHOTOS_STARTED =
  "ROUTE_GALLERY/UPLOAD_NEW_PHOTOS_STARTED";
export const ROUTE_GALLERY__UPLOAD_NEW_PHOTOS_SUCCEEDED =
  "ROUTE_GALLERY/UPLOAD_NEW_PHOTOS_SUCCEEDED";
export const ROUTE_GALLERY__UPLOAD_NEW_PHOTOS_FAILED =
  "ROUTE_GALLERY/UPLOAD_NEW_PHOTOS_FAILED";
export const ROUTE_GALLERY__RESET_STATE = "ROUTE_GALLERY/RESET_STATE";
