export const LOAD_ROUTES_SUCCESS = "LOAD_ROUTES_SUCCESS";
export const CREATE_ROUTE_SUCCESS = "CREATE_ROUTE_SUCCESS";
export const UPDATE_ROUTE_SUCCESS = "UPDATE_ROUTE_SUCCESS";
export const DELETE_ROUTE_SUCCESS = "DELETE_ROUTE_SUCCESS";
export const USER_LOGOUT = "USER_LOGOUT";

export const SIDEBAR_OPEN = "SIDEBAR_OPEN";
export const SIDEBAR_CLOSE = "SIDEBAR_CLOSE";

export const SELECT_PHOTO = "SELECT_PHOTO";
export const GET_NEXT_PHOTO = "GET_NEXT_PHOTO";
export const GET_PREV_PHOTO = "GET_PREV_PHOTO";
